### PR TITLE
Added Facebook Comments support. Corrected 2 words in Spanish translation.

### PR DESCRIPTION
**Pull request by rfmarves**
The Spanish translation needed 2 words corrected (I did the original translation under another account).  It's corrected.
 
Also modified three files to add Facebook comments support.  I tested it and it works well.  It'd my first time coding into a Static Site theme, if there's a better way to implement the feature, please recommend.

### CODE REVIEW

**Comment by liuyib** [comment]
@rfmarves  Awesome PR, thanks!
But I need to spend some time to get familiar with Facebook Comment. Soon the PR will be merged.

**Comment by liuyib** [comment]
@rfmarves via my test, the `colorscheme: dark` not take effect, so I removed it. Maybe it will be added in the future.
In addition, I didn't see the `appID` in the document of facebook, so I think the `appID` is no longer needed in the lateset version, so I also removed it.
Finally, I will test my changes temorrow. (Because my Facebook account has been blocked, I need to borrow my friend's Facebook account to test)

**Comment by rfmarves** [comment]
Thank you. I used with my app ID and it seemed to work. Thank you for taking the pull request.

**Comment by liuyib** [comment]
@rfmarves I did some compatibility work on facebook comment, now it is compatible with pjax.
In addition, I found that `appId` is used in `FB.init`, so I added it again.
Now, the PR will be merged. Thanks to you.

**Pull request merged**
